/* Generated by re2c 0.14.3 on Thu Oct 26 23:19:15 2017 */
#line 1 "lexer.re2c"
#include "lexer.h"

#define DECL_TOK_STR(Tok) #Tok,
const char *lexer_token_strings[] = {
    LEXER_ALL_TOKENS(DECL_TOK_STR)
};

#define TOK(Tok) return TOK_##Tok

int lexer_next_token(struct lexer_ctx *ctx, char **begin) {
    char *marker = (void *)0;
next_token_start:;
    *begin = ctx->cursor;

#line 18 "lexer.c"
{
	char yych;
	unsigned int yyaccept = 0;

	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy3;
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy7;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '%':	goto yy12;
	case '&':	goto yy14;
	case '(':	goto yy16;
	case ')':	goto yy18;
	case '*':	goto yy20;
	case '+':	goto yy22;
	case ',':	goto yy24;
	case '-':	goto yy26;
	case '/':	goto yy28;
	case '0':	goto yy30;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case ':':	goto yy34;
	case ';':	goto yy36;
	case '<':	goto yy38;
	case '=':	goto yy40;
	case '>':	goto yy42;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	case '^':	goto yy46;
	case 'e':	goto yy48;
	case 'f':	goto yy49;
	case 'i':	goto yy50;
	case 'l':	goto yy51;
	case 'm':	goto yy52;
	case 's':	goto yy53;
	case 'w':	goto yy54;
	case '|':	goto yy55;
	case '~':	goto yy57;
	default:	goto yy5;
	}
yy2:
#line 29 "lexer.re2c"
	{ goto next_token_start; }
#line 117 "lexer.c"
yy3:
	++ctx->cursor;
#line 27 "lexer.re2c"
	{ TOK(END); }
#line 122 "lexer.c"
yy5:
	++ctx->cursor;
#line 26 "lexer.re2c"
	{ TOK(ERR); }
#line 127 "lexer.c"
yy7:
	yych = *++ctx->cursor;
	goto yy139;
yy8:
	++ctx->cursor;
#line 35 "lexer.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 138 "lexer.c"
yy10:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '=':	goto yy136;
	default:	goto yy11;
	}
yy11:
#line 59 "lexer.re2c"
	{ TOK(NOT); }
#line 148 "lexer.c"
yy12:
	++ctx->cursor;
#line 51 "lexer.re2c"
	{ TOK(MOD); }
#line 153 "lexer.c"
yy14:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '&':	goto yy134;
	default:	goto yy15;
	}
yy15:
#line 55 "lexer.re2c"
	{ TOK(AND_BW); }
#line 163 "lexer.c"
yy16:
	++ctx->cursor;
#line 64 "lexer.re2c"
	{ TOK(LPAREN); }
#line 168 "lexer.c"
yy18:
	++ctx->cursor;
#line 65 "lexer.re2c"
	{ TOK(RPAREN); }
#line 173 "lexer.c"
yy20:
	++ctx->cursor;
#line 49 "lexer.re2c"
	{ TOK(MUL); }
#line 178 "lexer.c"
yy22:
	++ctx->cursor;
#line 47 "lexer.re2c"
	{ TOK(PLUS); }
#line 183 "lexer.c"
yy24:
	++ctx->cursor;
#line 61 "lexer.re2c"
	{ TOK(COMMA); }
#line 188 "lexer.c"
yy26:
	++ctx->cursor;
#line 48 "lexer.re2c"
	{ TOK(MINUS); }
#line 193 "lexer.c"
yy28:
	yyaccept = 0;
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case '/':	goto yy127;
	default:	goto yy29;
	}
yy29:
#line 50 "lexer.re2c"
	{ TOK(DIV); }
#line 204 "lexer.c"
yy30:
	yyaccept = 1;
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case 'B':
	case 'b':	goto yy120;
	case 'X':
	case 'x':	goto yy116;
	default:	goto yy119;
	}
yy31:
#line 80 "lexer.re2c"
	{ TOK(OCT); }
#line 218 "lexer.c"
yy32:
	++ctx->cursor;
	yych = *ctx->cursor;
	goto yy115;
yy33:
#line 81 "lexer.re2c"
	{ TOK(DEC); }
#line 226 "lexer.c"
yy34:
	++ctx->cursor;
#line 62 "lexer.re2c"
	{ TOK(COLON); }
#line 231 "lexer.c"
yy36:
	++ctx->cursor;
#line 63 "lexer.re2c"
	{ TOK(SEMICOLON); }
#line 236 "lexer.c"
yy38:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '<':	goto yy110;
	case '=':	goto yy112;
	default:	goto yy39;
	}
yy39:
#line 43 "lexer.re2c"
	{ TOK(LT); }
#line 247 "lexer.c"
yy40:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '=':	goto yy108;
	default:	goto yy41;
	}
yy41:
#line 40 "lexer.re2c"
	{ TOK(ASSIGN); }
#line 257 "lexer.c"
yy42:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '=':	goto yy106;
	case '>':	goto yy104;
	default:	goto yy43;
	}
yy43:
#line 44 "lexer.re2c"
	{ TOK(GT); }
#line 268 "lexer.c"
yy44:
	++ctx->cursor;
	yych = *ctx->cursor;
	goto yy62;
yy45:
#line 78 "lexer.re2c"
	{ TOK(IDENT); }
#line 276 "lexer.c"
yy46:
	++ctx->cursor;
#line 58 "lexer.re2c"
	{ TOK(XOR_BW); }
#line 281 "lexer.c"
yy48:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy97;
	default:	goto yy62;
	}
yy49:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy95;
	default:	goto yy62;
	}
yy50:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy83;
	case 'm':	goto yy85;
	case 'n':	goto yy86;
	default:	goto yy62;
	}
yy51:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy80;
	default:	goto yy62;
	}
yy52:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy74;
	default:	goto yy62;
	}
yy53:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy68;
	default:	goto yy62;
	}
yy54:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy63;
	default:	goto yy62;
	}
yy55:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '|':	goto yy59;
	default:	goto yy56;
	}
yy56:
#line 57 "lexer.re2c"
	{ TOK(OR_BW); }
#line 335 "lexer.c"
yy57:
	++ctx->cursor;
#line 60 "lexer.re2c"
	{ TOK(NOT_BW); }
#line 340 "lexer.c"
yy59:
	++ctx->cursor;
#line 56 "lexer.re2c"
	{ TOK(OR); }
#line 345 "lexer.c"
yy61:
	++ctx->cursor;
	yych = *ctx->cursor;
yy62:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy45;
	}
yy63:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy64;
	default:	goto yy62;
	}
yy64:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy65;
	default:	goto yy62;
	}
yy65:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy66;
	default:	goto yy62;
	}
yy66:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy67;
	}
yy67:
#line 75 "lexer.re2c"
	{ TOK(KW_WHILE); }
#line 505 "lexer.c"
yy68:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy69;
	default:	goto yy62;
	}
yy69:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy70;
	default:	goto yy62;
	}
yy70:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy71;
	default:	goto yy62;
	}
yy71:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy72;
	default:	goto yy62;
	}
yy72:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy73;
	}
yy73:
#line 68 "lexer.re2c"
	{ TOK(KW_STRUCT); }
#line 601 "lexer.c"
yy74:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy75;
	default:	goto yy62;
	}
yy75:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy76;
	default:	goto yy62;
	}
yy76:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy77;
	default:	goto yy62;
	}
yy77:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy78;
	default:	goto yy62;
	}
yy78:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy79;
	}
yy79:
#line 66 "lexer.re2c"
	{ TOK(KW_MODULE); }
#line 697 "lexer.c"
yy80:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy81;
	default:	goto yy62;
	}
yy81:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy82;
	}
yy82:
#line 70 "lexer.re2c"
	{ TOK(KW_LET); }
#line 775 "lexer.c"
yy83:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy84;
	}
yy84:
#line 72 "lexer.re2c"
	{ TOK(KW_IF); }
#line 847 "lexer.c"
yy85:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'p':	goto yy90;
	default:	goto yy62;
	}
yy86:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	case 't':	goto yy88;
	default:	goto yy87;
	}
yy87:
#line 71 "lexer.re2c"
	{ TOK(KW_IN); }
#line 925 "lexer.c"
yy88:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy89;
	}
yy89:
#line 76 "lexer.re2c"
	{ TOK(KW_INT); }
#line 997 "lexer.c"
yy90:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy91;
	default:	goto yy62;
	}
yy91:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy92;
	default:	goto yy62;
	}
yy92:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy93;
	default:	goto yy62;
	}
yy93:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy94;
	}
yy94:
#line 67 "lexer.re2c"
	{ TOK(KW_IMPORT); }
#line 1087 "lexer.c"
yy95:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy96;
	}
yy96:
#line 69 "lexer.re2c"
	{ TOK(KW_FN); }
#line 1159 "lexer.c"
yy97:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy98;
	case 's':	goto yy99;
	default:	goto yy62;
	}
yy98:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy102;
	default:	goto yy62;
	}
yy99:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy100;
	default:	goto yy62;
	}
yy100:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy101;
	}
yy101:
#line 74 "lexer.re2c"
	{ TOK(KW_ELSE); }
#line 1250 "lexer.c"
yy102:
	++ctx->cursor;
	switch ((yych = *ctx->cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy61;
	default:	goto yy103;
	}
yy103:
#line 73 "lexer.re2c"
	{ TOK(KW_ELIF); }
#line 1322 "lexer.c"
yy104:
	++ctx->cursor;
#line 53 "lexer.re2c"
	{ TOK(RSH); }
#line 1327 "lexer.c"
yy106:
	++ctx->cursor;
#line 46 "lexer.re2c"
	{ TOK(GTEQ); }
#line 1332 "lexer.c"
yy108:
	++ctx->cursor;
#line 41 "lexer.re2c"
	{ TOK(EQ); }
#line 1337 "lexer.c"
yy110:
	++ctx->cursor;
#line 52 "lexer.re2c"
	{ TOK(LSH); }
#line 1342 "lexer.c"
yy112:
	++ctx->cursor;
#line 45 "lexer.re2c"
	{ TOK(LTEQ); }
#line 1347 "lexer.c"
yy114:
	++ctx->cursor;
	yych = *ctx->cursor;
yy115:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy114;
	default:	goto yy33;
	}
yy116:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy124;
	default:	goto yy117;
	}
yy117:
	ctx->cursor = marker;
	switch (yyaccept) {
	case 0: 	goto yy29;
	case 1: 	goto yy31;
	default:	goto yy131;
	}
yy118:
	++ctx->cursor;
	yych = *ctx->cursor;
yy119:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy118;
	default:	goto yy31;
	}
yy120:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy121;
	default:	goto yy117;
	}
yy121:
	++ctx->cursor;
	yych = *ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy121;
	default:	goto yy123;
	}
yy123:
#line 79 "lexer.re2c"
	{ TOK(BIN); }
#line 1432 "lexer.c"
yy124:
	++ctx->cursor;
	yych = *ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy124;
	default:	goto yy126;
	}
yy126:
#line 82 "lexer.re2c"
	{ TOK(HEX); }
#line 1464 "lexer.c"
yy127:
	++ctx->cursor;
	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy129;
	case '\n':	goto yy132;
	default:	goto yy127;
	}
yy129:
	yyaccept = 2;
	marker = ++ctx->cursor;
	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy129;
	case '\n':	goto yy132;
	default:	goto yy127;
	}
yy131:
#line 30 "lexer.re2c"
	{ TOK(END); }
#line 1485 "lexer.c"
yy132:
	++ctx->cursor;
#line 31 "lexer.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 1493 "lexer.c"
yy134:
	++ctx->cursor;
#line 54 "lexer.re2c"
	{ TOK(AND); }
#line 1498 "lexer.c"
yy136:
	++ctx->cursor;
#line 42 "lexer.re2c"
	{ TOK(NEQ); }
#line 1503 "lexer.c"
yy138:
	++ctx->cursor;
	yych = *ctx->cursor;
yy139:
	switch (yych) {
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy138;
	default:	goto yy2;
	}
}
#line 83 "lexer.re2c"

}
