/* Generated by re2c 1.1.1 on Sat Mar 30 00:14:36 2019 */
#line 1 "scan.re2c"
#include "scan.h"

#define DECL_TOK_STR(Tok) #Tok,
const char *token_strings[] = {
    FOR_ALL_TOKENS(DECL_TOK_STR)
};

#define TOK(Tok) return TOK_##Tok

int scan_next_token(struct scan_ctx *ctx, char **begin) {
    char *marker = (void *)0;
next_token_start:;
    *begin = ctx->cursor;

#line 18 "scan.c"
{
	char yych;
	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '(':	goto yy17;
	case ')':	goto yy19;
	case '*':	goto yy21;
	case '+':	goto yy23;
	case ',':	goto yy25;
	case '-':	goto yy27;
	case '/':	goto yy29;
	case '0':	goto yy31;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	case ':':	goto yy36;
	case ';':	goto yy38;
	case '<':	goto yy40;
	case '=':	goto yy42;
	case '>':	goto yy44;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'q':
	case 'r':
	case 'u':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	case '[':	goto yy49;
	case ']':	goto yy51;
	case '^':	goto yy53;
	case 'a':	goto yy55;
	case 'b':	goto yy56;
	case 'c':	goto yy57;
	case 'd':	goto yy58;
	case 'e':	goto yy59;
	case 'f':	goto yy60;
	case 'i':	goto yy61;
	case 'l':	goto yy62;
	case 'm':	goto yy63;
	case 'n':	goto yy64;
	case 'o':	goto yy65;
	case 'p':	goto yy66;
	case 's':	goto yy67;
	case 't':	goto yy68;
	case 'v':	goto yy69;
	case 'w':	goto yy70;
	case '{':	goto yy71;
	case '|':	goto yy73;
	case '}':	goto yy75;
	case '~':	goto yy77;
	default:	goto yy4;
	}
yy2:
	++ctx->cursor;
#line 27 "scan.re2c"
	{ TOK(END); }
#line 120 "scan.c"
yy4:
	++ctx->cursor;
#line 26 "scan.re2c"
	{ TOK(ERR); }
#line 125 "scan.c"
yy6:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 29 "scan.re2c"
	{ goto next_token_start; }
#line 138 "scan.c"
yy9:
	++ctx->cursor;
#line 35 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 146 "scan.c"
yy11:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy79;
	default:	goto yy12;
	}
yy12:
#line 57 "scan.re2c"
	{ TOK(NOT); }
#line 156 "scan.c"
yy13:
	++ctx->cursor;
#line 51 "scan.re2c"
	{ TOK(MOD); }
#line 161 "scan.c"
yy15:
	++ctx->cursor;
#line 54 "scan.re2c"
	{ TOK(AND_BW); }
#line 166 "scan.c"
yy17:
	++ctx->cursor;
#line 62 "scan.re2c"
	{ TOK(LPAREN); }
#line 171 "scan.c"
yy19:
	++ctx->cursor;
#line 63 "scan.re2c"
	{ TOK(RPAREN); }
#line 176 "scan.c"
yy21:
	++ctx->cursor;
#line 49 "scan.re2c"
	{ TOK(MUL); }
#line 181 "scan.c"
yy23:
	++ctx->cursor;
#line 47 "scan.re2c"
	{ TOK(PLUS); }
#line 186 "scan.c"
yy25:
	++ctx->cursor;
#line 59 "scan.re2c"
	{ TOK(COMMA); }
#line 191 "scan.c"
yy27:
	yych = *++ctx->cursor;
	switch (yych) {
	case '>':	goto yy81;
	default:	goto yy28;
	}
yy28:
#line 48 "scan.re2c"
	{ TOK(MINUS); }
#line 201 "scan.c"
yy29:
	yych = *++ctx->cursor;
	switch (yych) {
	case '/':	goto yy83;
	default:	goto yy30;
	}
yy30:
#line 50 "scan.re2c"
	{ TOK(DIV); }
#line 211 "scan.c"
yy31:
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case 'B':
	case 'b':	goto yy87;
	case 'X':
	case 'x':	goto yy89;
	default:	goto yy86;
	}
yy32:
#line 101 "scan.re2c"
	{ TOK(OCT); }
#line 224 "scan.c"
yy33:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy35;
	}
yy35:
#line 102 "scan.re2c"
	{ TOK(DEC); }
#line 243 "scan.c"
yy36:
	++ctx->cursor;
#line 60 "scan.re2c"
	{ TOK(COLON); }
#line 248 "scan.c"
yy38:
	++ctx->cursor;
#line 61 "scan.re2c"
	{ TOK(SEMICOLON); }
#line 253 "scan.c"
yy40:
	yych = *++ctx->cursor;
	switch (yych) {
	case '-':	goto yy90;
	case '<':	goto yy92;
	case '=':	goto yy94;
	default:	goto yy41;
	}
yy41:
#line 43 "scan.re2c"
	{ TOK(LT); }
#line 265 "scan.c"
yy42:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy96;
	default:	goto yy43;
	}
yy43:
#line 40 "scan.re2c"
	{ TOK(ASSIGN); }
#line 275 "scan.c"
yy44:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy98;
	case '>':	goto yy100;
	default:	goto yy45;
	}
yy45:
#line 44 "scan.re2c"
	{ TOK(GT); }
#line 286 "scan.c"
yy46:
	yych = *++ctx->cursor;
yy47:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy48;
	}
yy48:
#line 99 "scan.re2c"
	{ TOK(IDENT); }
#line 359 "scan.c"
yy49:
	++ctx->cursor;
#line 64 "scan.re2c"
	{ TOK(LBRACKET); }
#line 364 "scan.c"
yy51:
	++ctx->cursor;
#line 65 "scan.re2c"
	{ TOK(RBRACKET); }
#line 369 "scan.c"
yy53:
	++ctx->cursor;
#line 56 "scan.re2c"
	{ TOK(XOR_BW); }
#line 374 "scan.c"
yy55:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy102;
	default:	goto yy47;
	}
yy56:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy103;
	default:	goto yy47;
	}
yy57:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy104;
	case 'o':	goto yy105;
	default:	goto yy47;
	}
yy58:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy106;
	case 'o':	goto yy107;
	default:	goto yy47;
	}
yy59:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy109;
	case 'n':	goto yy110;
	default:	goto yy47;
	}
yy60:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy111;
	case 'o':	goto yy112;
	case 'u':	goto yy113;
	default:	goto yy47;
	}
yy61:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy114;
	case 'm':	goto yy116;
	case 'n':	goto yy117;
	default:	goto yy47;
	}
yy62:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy119;
	default:	goto yy47;
	}
yy63:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy120;
	default:	goto yy47;
	}
yy64:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy121;
	default:	goto yy47;
	}
yy65:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy122;
	case 'r':	goto yy124;
	default:	goto yy47;
	}
yy66:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy126;
	default:	goto yy47;
	}
yy67:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy127;
	default:	goto yy47;
	}
yy68:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy128;
	case 'r':	goto yy129;
	default:	goto yy47;
	}
yy69:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy130;
	default:	goto yy47;
	}
yy70:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy131;
	default:	goto yy47;
	}
yy71:
	++ctx->cursor;
#line 66 "scan.re2c"
	{ TOK(LBRACE); }
#line 484 "scan.c"
yy73:
	++ctx->cursor;
#line 55 "scan.re2c"
	{ TOK(OR_BW); }
#line 489 "scan.c"
yy75:
	++ctx->cursor;
#line 67 "scan.re2c"
	{ TOK(RBRACE); }
#line 494 "scan.c"
yy77:
	++ctx->cursor;
#line 58 "scan.re2c"
	{ TOK(NOT_BW); }
#line 499 "scan.c"
yy79:
	++ctx->cursor;
#line 42 "scan.re2c"
	{ TOK(NEQ); }
#line 504 "scan.c"
yy81:
	++ctx->cursor;
#line 68 "scan.re2c"
	{ TOK(RARROW); }
#line 509 "scan.c"
yy83:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\n':	goto yy132;
	default:	goto yy83;
	}
yy85:
	yych = *++ctx->cursor;
yy86:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy85;
	default:	goto yy32;
	}
yy87:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy134;
	default:	goto yy88;
	}
yy88:
	ctx->cursor = marker;
	goto yy32;
yy89:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	default:	goto yy88;
	}
yy90:
	++ctx->cursor;
#line 69 "scan.re2c"
	{ TOK(LARROW); }
#line 571 "scan.c"
yy92:
	++ctx->cursor;
#line 52 "scan.re2c"
	{ TOK(LSH); }
#line 576 "scan.c"
yy94:
	++ctx->cursor;
#line 45 "scan.re2c"
	{ TOK(LTEQ); }
#line 581 "scan.c"
yy96:
	++ctx->cursor;
#line 41 "scan.re2c"
	{ TOK(EQ); }
#line 586 "scan.c"
yy98:
	++ctx->cursor;
#line 46 "scan.re2c"
	{ TOK(GTEQ); }
#line 591 "scan.c"
yy100:
	++ctx->cursor;
#line 53 "scan.re2c"
	{ TOK(RSH); }
#line 596 "scan.c"
yy102:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy140;
	default:	goto yy47;
	}
yy103:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'g':	goto yy142;
	default:	goto yy47;
	}
yy104:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy143;
	default:	goto yy47;
	}
yy105:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy144;
	default:	goto yy47;
	}
yy106:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy145;
	default:	goto yy47;
	}
yy107:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy108;
	}
yy108:
#line 88 "scan.re2c"
	{ TOK(KW_DO); }
#line 698 "scan.c"
yy109:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy147;
	case 's':	goto yy148;
	default:	goto yy47;
	}
yy110:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy149;
	default:	goto yy47;
	}
yy111:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy151;
	default:	goto yy47;
	}
yy112:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy152;
	default:	goto yy47;
	}
yy113:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy154;
	default:	goto yy47;
	}
yy114:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy115;
	}
yy115:
#line 82 "scan.re2c"
	{ TOK(KW_IF); }
#line 801 "scan.c"
yy116:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'p':	goto yy156;
	default:	goto yy47;
	}
yy117:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy118;
	}
yy118:
#line 81 "scan.re2c"
	{ TOK(KW_IN); }
#line 879 "scan.c"
yy119:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy157;
	default:	goto yy47;
	}
yy120:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy159;
	default:	goto yy47;
	}
yy121:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy160;
	default:	goto yy47;
	}
yy122:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy123;
	}
yy123:
#line 87 "scan.re2c"
	{ TOK(KW_OF); }
#line 969 "scan.c"
yy124:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy125;
	}
yy125:
#line 96 "scan.re2c"
	{ TOK(KW_OR); }
#line 1041 "scan.c"
yy126:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'b':	goto yy162;
	case 'r':	goto yy164;
	default:	goto yy47;
	}
yy127:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy165;
	case 'r':	goto yy166;
	default:	goto yy47;
	}
yy128:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy167;
	default:	goto yy47;
	}
yy129:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy168;
	default:	goto yy47;
	}
yy130:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy169;
	default:	goto yy47;
	}
yy131:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy171;
	default:	goto yy47;
	}
yy132:
	++ctx->cursor;
#line 31 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 1087 "scan.c"
yy134:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy134;
	default:	goto yy136;
	}
yy136:
#line 100 "scan.re2c"
	{ TOK(BIN); }
#line 1098 "scan.c"
yy137:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy137;
	default:	goto yy139;
	}
yy139:
#line 103 "scan.re2c"
	{ TOK(HEX); }
#line 1129 "scan.c"
yy140:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy141;
	}
yy141:
#line 95 "scan.re2c"
	{ TOK(KW_AND); }
#line 1201 "scan.c"
yy142:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy172;
	default:	goto yy47;
	}
yy143:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy173;
	default:	goto yy47;
	}
yy144:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy175;
	default:	goto yy47;
	}
yy145:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy146;
	}
yy146:
#line 76 "scan.re2c"
	{ TOK(KW_DEF); }
#line 1291 "scan.c"
yy147:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy176;
	default:	goto yy47;
	}
yy148:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy178;
	default:	goto yy47;
	}
yy149:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy150;
	}
yy150:
#line 71 "scan.re2c"
	{ TOK(KW_END); }
#line 1375 "scan.c"
yy151:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy180;
	default:	goto yy47;
	}
yy152:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy153;
	}
yy153:
#line 89 "scan.re2c"
	{ TOK(KW_FOR); }
#line 1453 "scan.c"
yy154:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy155;
	}
yy155:
#line 75 "scan.re2c"
	{ TOK(KW_FUN); }
#line 1525 "scan.c"
yy156:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy181;
	default:	goto yy47;
	}
yy157:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy158;
	}
yy158:
#line 80 "scan.re2c"
	{ TOK(KW_LET); }
#line 1603 "scan.c"
yy159:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy182;
	default:	goto yy47;
	}
yy160:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy161;
	}
yy161:
#line 97 "scan.re2c"
	{ TOK(KW_NOT); }
#line 1681 "scan.c"
yy162:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy163;
	}
yy163:
#line 77 "scan.re2c"
	{ TOK(KW_PUB); }
#line 1753 "scan.c"
yy164:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy183;
	default:	goto yy47;
	}
yy165:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy185;
	default:	goto yy47;
	}
yy166:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy186;
	default:	goto yy47;
	}
yy167:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy187;
	default:	goto yy47;
	}
yy168:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy189;
	default:	goto yy47;
	}
yy169:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy170;
	}
yy170:
#line 79 "scan.re2c"
	{ TOK(KW_VAR); }
#line 1855 "scan.c"
yy171:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy191;
	default:	goto yy47;
	}
yy172:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy192;
	default:	goto yy47;
	}
yy173:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy174;
	}
yy174:
#line 86 "scan.re2c"
	{ TOK(KW_CASE); }
#line 1939 "scan.c"
yy175:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy194;
	default:	goto yy47;
	}
yy176:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy177;
	}
yy177:
#line 84 "scan.re2c"
	{ TOK(KW_ELIF); }
#line 2017 "scan.c"
yy178:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy179;
	}
yy179:
#line 85 "scan.re2c"
	{ TOK(KW_ELSE); }
#line 2089 "scan.c"
yy180:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy196;
	default:	goto yy47;
	}
yy181:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy198;
	default:	goto yy47;
	}
yy182:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy199;
	default:	goto yy47;
	}
yy183:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy184;
	}
yy184:
#line 92 "scan.re2c"
	{ TOK(KW_PURE); }
#line 2179 "scan.c"
yy185:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy200;
	default:	goto yy47;
	}
yy186:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy201;
	default:	goto yy47;
	}
yy187:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy188;
	}
yy188:
#line 83 "scan.re2c"
	{ TOK(KW_THEN); }
#line 2263 "scan.c"
yy189:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy190;
	}
yy190:
#line 93 "scan.re2c"
	{ TOK(KW_TRUE); }
#line 2335 "scan.c"
yy191:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy202;
	default:	goto yy47;
	}
yy192:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy193;
	}
yy193:
#line 70 "scan.re2c"
	{ TOK(KW_BEGIN); }
#line 2413 "scan.c"
yy194:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy195;
	}
yy195:
#line 78 "scan.re2c"
	{ TOK(KW_CONST); }
#line 2485 "scan.c"
yy196:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy197;
	}
yy197:
#line 94 "scan.re2c"
	{ TOK(KW_FALSE); }
#line 2557 "scan.c"
yy198:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy204;
	default:	goto yy47;
	}
yy199:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy206;
	default:	goto yy47;
	}
yy200:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy208;
	default:	goto yy47;
	}
yy201:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy210;
	default:	goto yy47;
	}
yy202:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy203;
	}
yy203:
#line 90 "scan.re2c"
	{ TOK(KW_WHILE); }
#line 2653 "scan.c"
yy204:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy205;
	}
yy205:
#line 73 "scan.re2c"
	{ TOK(KW_IMPORT); }
#line 2725 "scan.c"
yy206:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy207;
	}
yy207:
#line 72 "scan.re2c"
	{ TOK(KW_MODULE); }
#line 2797 "scan.c"
yy208:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy209;
	}
yy209:
#line 91 "scan.re2c"
	{ TOK(KW_STATIC); }
#line 2869 "scan.c"
yy210:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy211;
	}
yy211:
#line 74 "scan.re2c"
	{ TOK(KW_STRUCT); }
#line 2941 "scan.c"
}
#line 104 "scan.re2c"

}
