/* Generated by re2c 1.1.1 on Tue Apr  9 22:54:40 2019 */
#line 1 "scan.re2c"
#include "scan.h"

#define DECL_TOK_STR(Tok) #Tok,
const char *token_strings[] = {
    FOR_ALL_TOKENS(DECL_TOK_STR)
};

#define TOK(Tok) return TOK_##Tok

int scan_next_token(struct scan_ctx *ctx, char **begin) {
    char *marker = (void *)0;
next_token_start:;
    *begin = ctx->cursor;

#line 18 "scan.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '"':	goto yy13;
	case '%':	goto yy15;
	case '&':	goto yy17;
	case '(':	goto yy19;
	case ')':	goto yy21;
	case '*':	goto yy23;
	case '+':	goto yy25;
	case ',':	goto yy27;
	case '-':	goto yy29;
	case '.':	goto yy31;
	case '/':	goto yy33;
	case '0':	goto yy35;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	case ':':	goto yy40;
	case ';':	goto yy42;
	case '<':	goto yy44;
	case '=':	goto yy46;
	case '>':	goto yy48;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'q':
	case 'r':
	case 'u':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	case '[':	goto yy53;
	case ']':	goto yy55;
	case '^':	goto yy57;
	case 'a':	goto yy59;
	case 'b':	goto yy60;
	case 'c':	goto yy61;
	case 'd':	goto yy62;
	case 'e':	goto yy63;
	case 'f':	goto yy64;
	case 'i':	goto yy65;
	case 'l':	goto yy66;
	case 'm':	goto yy67;
	case 'n':	goto yy68;
	case 'o':	goto yy69;
	case 'p':	goto yy70;
	case 's':	goto yy71;
	case 't':	goto yy72;
	case 'v':	goto yy73;
	case 'w':	goto yy74;
	case '{':	goto yy75;
	case '|':	goto yy77;
	case '}':	goto yy79;
	case '~':	goto yy81;
	default:	goto yy4;
	}
yy2:
	++ctx->cursor;
#line 32 "scan.re2c"
	{ TOK(END); }
#line 123 "scan.c"
yy4:
	++ctx->cursor;
#line 31 "scan.re2c"
	{ TOK(ERR); }
#line 128 "scan.c"
yy6:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 34 "scan.re2c"
	{ goto next_token_start; }
#line 141 "scan.c"
yy9:
	++ctx->cursor;
#line 40 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 149 "scan.c"
yy11:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy83;
	default:	goto yy12;
	}
yy12:
#line 62 "scan.re2c"
	{ TOK(NOT); }
#line 159 "scan.c"
yy13:
	yych = *++ctx->cursor;
	switch (yych) {
	case '"':	goto yy85;
	default:	goto yy13;
	}
yy15:
	++ctx->cursor;
#line 56 "scan.re2c"
	{ TOK(MOD); }
#line 170 "scan.c"
yy17:
	++ctx->cursor;
#line 59 "scan.re2c"
	{ TOK(AND_BW); }
#line 175 "scan.c"
yy19:
	++ctx->cursor;
#line 68 "scan.re2c"
	{ TOK(LPAREN); }
#line 180 "scan.c"
yy21:
	++ctx->cursor;
#line 69 "scan.re2c"
	{ TOK(RPAREN); }
#line 185 "scan.c"
yy23:
	++ctx->cursor;
#line 54 "scan.re2c"
	{ TOK(MUL); }
#line 190 "scan.c"
yy25:
	++ctx->cursor;
#line 52 "scan.re2c"
	{ TOK(PLUS); }
#line 195 "scan.c"
yy27:
	++ctx->cursor;
#line 64 "scan.re2c"
	{ TOK(COMMA); }
#line 200 "scan.c"
yy29:
	yych = *++ctx->cursor;
	switch (yych) {
	case '>':	goto yy87;
	default:	goto yy30;
	}
yy30:
#line 53 "scan.re2c"
	{ TOK(MINUS); }
#line 210 "scan.c"
yy31:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy89;
	default:	goto yy32;
	}
yy32:
#line 65 "scan.re2c"
	{ TOK(PERIOD); }
#line 229 "scan.c"
yy33:
	yych = *++ctx->cursor;
	switch (yych) {
	case '/':	goto yy92;
	default:	goto yy34;
	}
yy34:
#line 55 "scan.re2c"
	{ TOK(DIV); }
#line 239 "scan.c"
yy35:
	yyaccept = 0;
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case 'B':
	case 'b':	goto yy99;
	case 'X':
	case 'x':	goto yy101;
	default:	goto yy95;
	}
yy36:
#line 108 "scan.re2c"
	{ TOK(OCT); }
#line 253 "scan.c"
yy37:
	yyaccept = 1;
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case '.':	goto yy89;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy39;
	}
yy39:
#line 109 "scan.re2c"
	{ TOK(DEC); }
#line 276 "scan.c"
yy40:
	++ctx->cursor;
#line 66 "scan.re2c"
	{ TOK(COLON); }
#line 281 "scan.c"
yy42:
	++ctx->cursor;
#line 67 "scan.re2c"
	{ TOK(SEMICOLON); }
#line 286 "scan.c"
yy44:
	yych = *++ctx->cursor;
	switch (yych) {
	case '-':	goto yy102;
	case '<':	goto yy104;
	case '=':	goto yy106;
	default:	goto yy45;
	}
yy45:
#line 48 "scan.re2c"
	{ TOK(LT); }
#line 298 "scan.c"
yy46:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy108;
	default:	goto yy47;
	}
yy47:
#line 45 "scan.re2c"
	{ TOK(ASSIGN); }
#line 308 "scan.c"
yy48:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy110;
	case '>':	goto yy112;
	default:	goto yy49;
	}
yy49:
#line 49 "scan.re2c"
	{ TOK(GT); }
#line 319 "scan.c"
yy50:
	yych = *++ctx->cursor;
yy51:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy52;
	}
yy52:
#line 106 "scan.re2c"
	{ TOK(IDENT); }
#line 392 "scan.c"
yy53:
	++ctx->cursor;
#line 70 "scan.re2c"
	{ TOK(LBRACKET); }
#line 397 "scan.c"
yy55:
	++ctx->cursor;
#line 71 "scan.re2c"
	{ TOK(RBRACKET); }
#line 402 "scan.c"
yy57:
	++ctx->cursor;
#line 61 "scan.re2c"
	{ TOK(XOR_BW); }
#line 407 "scan.c"
yy59:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy114;
	default:	goto yy51;
	}
yy60:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy115;
	default:	goto yy51;
	}
yy61:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy116;
	case 'o':	goto yy117;
	default:	goto yy51;
	}
yy62:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy118;
	case 'o':	goto yy119;
	default:	goto yy51;
	}
yy63:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy121;
	case 'n':	goto yy122;
	default:	goto yy51;
	}
yy64:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy123;
	case 'o':	goto yy124;
	case 'u':	goto yy125;
	default:	goto yy51;
	}
yy65:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy126;
	case 'm':	goto yy128;
	case 'n':	goto yy129;
	default:	goto yy51;
	}
yy66:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy131;
	default:	goto yy51;
	}
yy67:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy132;
	default:	goto yy51;
	}
yy68:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy133;
	default:	goto yy51;
	}
yy69:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy134;
	case 'r':	goto yy136;
	default:	goto yy51;
	}
yy70:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy138;
	default:	goto yy51;
	}
yy71:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy139;
	case 't':	goto yy140;
	default:	goto yy51;
	}
yy72:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy141;
	case 'r':	goto yy142;
	default:	goto yy51;
	}
yy73:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy143;
	default:	goto yy51;
	}
yy74:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy144;
	default:	goto yy51;
	}
yy75:
	++ctx->cursor;
#line 72 "scan.re2c"
	{ TOK(LBRACE); }
#line 518 "scan.c"
yy77:
	++ctx->cursor;
#line 60 "scan.re2c"
	{ TOK(OR_BW); }
#line 523 "scan.c"
yy79:
	++ctx->cursor;
#line 73 "scan.re2c"
	{ TOK(RBRACE); }
#line 528 "scan.c"
yy81:
	++ctx->cursor;
#line 63 "scan.re2c"
	{ TOK(NOT_BW); }
#line 533 "scan.c"
yy83:
	++ctx->cursor;
#line 47 "scan.re2c"
	{ TOK(NEQ); }
#line 538 "scan.c"
yy85:
	++ctx->cursor;
#line 112 "scan.re2c"
	{ TOK(STRING); }
#line 543 "scan.c"
yy87:
	++ctx->cursor;
#line 74 "scan.re2c"
	{ TOK(RARROW); }
#line 548 "scan.c"
yy89:
	yyaccept = 2;
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy89;
	case 'E':
	case 'e':	goto yy100;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy145;
	default:	goto yy91;
	}
yy91:
#line 111 "scan.re2c"
	{ TOK(REAL); }
#line 574 "scan.c"
yy92:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\n':	goto yy146;
	default:	goto yy92;
	}
yy94:
	yyaccept = 0;
	yych = *(marker = ++ctx->cursor);
yy95:
	switch (yych) {
	case '.':	goto yy89;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy94;
	case '8':
	case '9':	goto yy96;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy36;
	}
yy96:
	yych = *++ctx->cursor;
	switch (yych) {
	case '.':	goto yy89;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy96;
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy98;
	}
yy98:
	ctx->cursor = marker;
	switch (yyaccept) {
	case 0: 	goto yy36;
	case 1: 	goto yy39;
	default:	goto yy91;
	}
yy99:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy148;
	default:	goto yy98;
	}
yy100:
	yych = *++ctx->cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy151;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	default:	goto yy98;
	}
yy101:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy154;
	default:	goto yy98;
	}
yy102:
	++ctx->cursor;
#line 75 "scan.re2c"
	{ TOK(LARROW); }
#line 681 "scan.c"
yy104:
	++ctx->cursor;
#line 57 "scan.re2c"
	{ TOK(LSH); }
#line 686 "scan.c"
yy106:
	++ctx->cursor;
#line 50 "scan.re2c"
	{ TOK(LTEQ); }
#line 691 "scan.c"
yy108:
	++ctx->cursor;
#line 46 "scan.re2c"
	{ TOK(EQ); }
#line 696 "scan.c"
yy110:
	++ctx->cursor;
#line 51 "scan.re2c"
	{ TOK(GTEQ); }
#line 701 "scan.c"
yy112:
	++ctx->cursor;
#line 58 "scan.re2c"
	{ TOK(RSH); }
#line 706 "scan.c"
yy114:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy157;
	default:	goto yy51;
	}
yy115:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'g':	goto yy159;
	default:	goto yy51;
	}
yy116:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy160;
	default:	goto yy51;
	}
yy117:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy161;
	default:	goto yy51;
	}
yy118:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy162;
	default:	goto yy51;
	}
yy119:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy120;
	}
yy120:
#line 95 "scan.re2c"
	{ TOK(KW_DO); }
#line 808 "scan.c"
yy121:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy164;
	case 's':	goto yy165;
	default:	goto yy51;
	}
yy122:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy166;
	default:	goto yy51;
	}
yy123:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy168;
	default:	goto yy51;
	}
yy124:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy169;
	default:	goto yy51;
	}
yy125:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy171;
	default:	goto yy51;
	}
yy126:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy127;
	}
yy127:
#line 89 "scan.re2c"
	{ TOK(KW_IF); }
#line 911 "scan.c"
yy128:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'p':	goto yy173;
	default:	goto yy51;
	}
yy129:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy130;
	}
yy130:
#line 88 "scan.re2c"
	{ TOK(KW_IN); }
#line 989 "scan.c"
yy131:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy174;
	default:	goto yy51;
	}
yy132:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy176;
	default:	goto yy51;
	}
yy133:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy177;
	default:	goto yy51;
	}
yy134:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy135;
	}
yy135:
#line 94 "scan.re2c"
	{ TOK(KW_OF); }
#line 1079 "scan.c"
yy136:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy137;
	}
yy137:
#line 103 "scan.re2c"
	{ TOK(KW_OR); }
#line 1151 "scan.c"
yy138:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'b':	goto yy179;
	case 'r':	goto yy181;
	default:	goto yy51;
	}
yy139:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy182;
	default:	goto yy51;
	}
yy140:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy183;
	case 'r':	goto yy184;
	default:	goto yy51;
	}
yy141:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy185;
	default:	goto yy51;
	}
yy142:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy186;
	default:	goto yy51;
	}
yy143:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy187;
	default:	goto yy51;
	}
yy144:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy189;
	default:	goto yy51;
	}
yy145:
	++ctx->cursor;
	goto yy91;
yy146:
	++ctx->cursor;
#line 36 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 1206 "scan.c"
yy148:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy148;
	default:	goto yy150;
	}
yy150:
#line 107 "scan.re2c"
	{ TOK(BIN); }
#line 1217 "scan.c"
yy151:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	default:	goto yy98;
	}
yy152:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy145;
	default:	goto yy91;
	}
yy154:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy154;
	default:	goto yy156;
	}
yy156:
#line 110 "scan.re2c"
	{ TOK(HEX); }
#line 1282 "scan.c"
yy157:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy158;
	}
yy158:
#line 102 "scan.re2c"
	{ TOK(KW_AND); }
#line 1354 "scan.c"
yy159:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy190;
	default:	goto yy51;
	}
yy160:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy191;
	default:	goto yy51;
	}
yy161:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy193;
	default:	goto yy51;
	}
yy162:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy163;
	}
yy163:
#line 83 "scan.re2c"
	{ TOK(KW_DEF); }
#line 1444 "scan.c"
yy164:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy194;
	default:	goto yy51;
	}
yy165:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy196;
	default:	goto yy51;
	}
yy166:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy167;
	}
yy167:
#line 77 "scan.re2c"
	{ TOK(KW_END); }
#line 1528 "scan.c"
yy168:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy198;
	default:	goto yy51;
	}
yy169:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy170;
	}
yy170:
#line 96 "scan.re2c"
	{ TOK(KW_FOR); }
#line 1606 "scan.c"
yy171:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy172;
	}
yy172:
#line 82 "scan.re2c"
	{ TOK(KW_FUN); }
#line 1678 "scan.c"
yy173:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy199;
	default:	goto yy51;
	}
yy174:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy175;
	}
yy175:
#line 87 "scan.re2c"
	{ TOK(KW_LET); }
#line 1756 "scan.c"
yy176:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy200;
	default:	goto yy51;
	}
yy177:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy178;
	}
yy178:
#line 104 "scan.re2c"
	{ TOK(KW_NOT); }
#line 1834 "scan.c"
yy179:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy180;
	}
yy180:
#line 84 "scan.re2c"
	{ TOK(KW_PUB); }
#line 1906 "scan.c"
yy181:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy201;
	default:	goto yy51;
	}
yy182:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy203;
	default:	goto yy51;
	}
yy183:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy205;
	default:	goto yy51;
	}
yy184:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy206;
	default:	goto yy51;
	}
yy185:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy207;
	default:	goto yy51;
	}
yy186:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy209;
	default:	goto yy51;
	}
yy187:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy188;
	}
yy188:
#line 86 "scan.re2c"
	{ TOK(KW_VAR); }
#line 2014 "scan.c"
yy189:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy211;
	default:	goto yy51;
	}
yy190:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy212;
	default:	goto yy51;
	}
yy191:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy192;
	}
yy192:
#line 93 "scan.re2c"
	{ TOK(KW_CASE); }
#line 2098 "scan.c"
yy193:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy214;
	default:	goto yy51;
	}
yy194:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy195;
	}
yy195:
#line 91 "scan.re2c"
	{ TOK(KW_ELIF); }
#line 2176 "scan.c"
yy196:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy197;
	}
yy197:
#line 92 "scan.re2c"
	{ TOK(KW_ELSE); }
#line 2248 "scan.c"
yy198:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy216;
	default:	goto yy51;
	}
yy199:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy218;
	default:	goto yy51;
	}
yy200:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy219;
	default:	goto yy51;
	}
yy201:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy202;
	}
yy202:
#line 99 "scan.re2c"
	{ TOK(KW_PURE); }
#line 2338 "scan.c"
yy203:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy204;
	}
yy204:
#line 81 "scan.re2c"
	{ TOK(KW_SELF); }
#line 2410 "scan.c"
yy205:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy220;
	default:	goto yy51;
	}
yy206:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy221;
	default:	goto yy51;
	}
yy207:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy208;
	}
yy208:
#line 90 "scan.re2c"
	{ TOK(KW_THEN); }
#line 2494 "scan.c"
yy209:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy210;
	}
yy210:
#line 100 "scan.re2c"
	{ TOK(KW_TRUE); }
#line 2566 "scan.c"
yy211:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy222;
	default:	goto yy51;
	}
yy212:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy213;
	}
yy213:
#line 76 "scan.re2c"
	{ TOK(KW_BEGIN); }
#line 2644 "scan.c"
yy214:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy215;
	}
yy215:
#line 85 "scan.re2c"
	{ TOK(KW_CONST); }
#line 2716 "scan.c"
yy216:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy217;
	}
yy217:
#line 101 "scan.re2c"
	{ TOK(KW_FALSE); }
#line 2788 "scan.c"
yy218:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy224;
	default:	goto yy51;
	}
yy219:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy226;
	default:	goto yy51;
	}
yy220:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy228;
	default:	goto yy51;
	}
yy221:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy230;
	default:	goto yy51;
	}
yy222:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy223;
	}
yy223:
#line 97 "scan.re2c"
	{ TOK(KW_WHILE); }
#line 2884 "scan.c"
yy224:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy225;
	}
yy225:
#line 79 "scan.re2c"
	{ TOK(KW_IMPORT); }
#line 2956 "scan.c"
yy226:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy227;
	}
yy227:
#line 78 "scan.re2c"
	{ TOK(KW_MODULE); }
#line 3028 "scan.c"
yy228:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy229;
	}
yy229:
#line 98 "scan.re2c"
	{ TOK(KW_STATIC); }
#line 3100 "scan.c"
yy230:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy50;
	default:	goto yy231;
	}
yy231:
#line 80 "scan.re2c"
	{ TOK(KW_STRUCT); }
#line 3172 "scan.c"
}
#line 113 "scan.re2c"

}
