/* Generated by re2c 1.1.1 on Sat Jan 19 01:33:35 2019 */
#line 1 "scan.re2c"
#include "scan.h"

#define DECL_TOK_STR(Tok) #Tok,
const char *token_strings[] = {
    FOR_ALL_TOKENS(DECL_TOK_STR)
};

#define TOK(Tok) return TOK_##Tok

int scan_next_token(struct scan_ctx *ctx, char **begin) {
    char *marker = (void *)0;
next_token_start:;
    *begin = ctx->cursor;

#line 18 "scan.c"
{
	char yych;
	yych = *ctx->cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '(':	goto yy17;
	case ')':	goto yy19;
	case '*':	goto yy21;
	case '+':	goto yy23;
	case ',':	goto yy25;
	case '-':	goto yy27;
	case '/':	goto yy29;
	case '0':	goto yy31;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	case ':':	goto yy36;
	case ';':	goto yy38;
	case '<':	goto yy40;
	case '=':	goto yy42;
	case '>':	goto yy44;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'n':
	case 'q':
	case 'r':
	case 'u':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	case '[':	goto yy49;
	case ']':	goto yy51;
	case '^':	goto yy53;
	case 'b':	goto yy55;
	case 'c':	goto yy56;
	case 'd':	goto yy57;
	case 'e':	goto yy58;
	case 'f':	goto yy59;
	case 'i':	goto yy60;
	case 'l':	goto yy61;
	case 'm':	goto yy62;
	case 'o':	goto yy63;
	case 'p':	goto yy64;
	case 's':	goto yy65;
	case 't':	goto yy66;
	case 'v':	goto yy67;
	case 'w':	goto yy68;
	case '{':	goto yy69;
	case '|':	goto yy71;
	case '}':	goto yy73;
	case '~':	goto yy75;
	default:	goto yy4;
	}
yy2:
	++ctx->cursor;
#line 27 "scan.re2c"
	{ TOK(END); }
#line 120 "scan.c"
yy4:
	++ctx->cursor;
#line 26 "scan.re2c"
	{ TOK(ERR); }
#line 125 "scan.c"
yy6:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\t':
	case '\v':
	case '\r':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 29 "scan.re2c"
	{ goto next_token_start; }
#line 138 "scan.c"
yy9:
	++ctx->cursor;
#line 35 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 146 "scan.c"
yy11:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy77;
	default:	goto yy12;
	}
yy12:
#line 59 "scan.re2c"
	{ TOK(NOT); }
#line 156 "scan.c"
yy13:
	++ctx->cursor;
#line 51 "scan.re2c"
	{ TOK(MOD); }
#line 161 "scan.c"
yy15:
	yych = *++ctx->cursor;
	switch (yych) {
	case '&':	goto yy79;
	default:	goto yy16;
	}
yy16:
#line 55 "scan.re2c"
	{ TOK(AND_BW); }
#line 171 "scan.c"
yy17:
	++ctx->cursor;
#line 64 "scan.re2c"
	{ TOK(LPAREN); }
#line 176 "scan.c"
yy19:
	++ctx->cursor;
#line 65 "scan.re2c"
	{ TOK(RPAREN); }
#line 181 "scan.c"
yy21:
	++ctx->cursor;
#line 49 "scan.re2c"
	{ TOK(MUL); }
#line 186 "scan.c"
yy23:
	++ctx->cursor;
#line 47 "scan.re2c"
	{ TOK(PLUS); }
#line 191 "scan.c"
yy25:
	++ctx->cursor;
#line 61 "scan.re2c"
	{ TOK(COMMA); }
#line 196 "scan.c"
yy27:
	yych = *++ctx->cursor;
	switch (yych) {
	case '>':	goto yy81;
	default:	goto yy28;
	}
yy28:
#line 48 "scan.re2c"
	{ TOK(MINUS); }
#line 206 "scan.c"
yy29:
	yych = *++ctx->cursor;
	switch (yych) {
	case '/':	goto yy83;
	default:	goto yy30;
	}
yy30:
#line 50 "scan.re2c"
	{ TOK(DIV); }
#line 216 "scan.c"
yy31:
	yych = *(marker = ++ctx->cursor);
	switch (yych) {
	case 'B':
	case 'b':	goto yy87;
	case 'X':
	case 'x':	goto yy89;
	default:	goto yy86;
	}
yy32:
#line 98 "scan.re2c"
	{ TOK(OCT); }
#line 229 "scan.c"
yy33:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	default:	goto yy35;
	}
yy35:
#line 99 "scan.re2c"
	{ TOK(DEC); }
#line 248 "scan.c"
yy36:
	++ctx->cursor;
#line 62 "scan.re2c"
	{ TOK(COLON); }
#line 253 "scan.c"
yy38:
	++ctx->cursor;
#line 63 "scan.re2c"
	{ TOK(SEMICOLON); }
#line 258 "scan.c"
yy40:
	yych = *++ctx->cursor;
	switch (yych) {
	case '-':	goto yy90;
	case '<':	goto yy92;
	case '=':	goto yy94;
	default:	goto yy41;
	}
yy41:
#line 43 "scan.re2c"
	{ TOK(LT); }
#line 270 "scan.c"
yy42:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy96;
	default:	goto yy43;
	}
yy43:
#line 40 "scan.re2c"
	{ TOK(ASSIGN); }
#line 280 "scan.c"
yy44:
	yych = *++ctx->cursor;
	switch (yych) {
	case '=':	goto yy98;
	case '>':	goto yy100;
	default:	goto yy45;
	}
yy45:
#line 44 "scan.re2c"
	{ TOK(GT); }
#line 291 "scan.c"
yy46:
	yych = *++ctx->cursor;
yy47:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy48;
	}
yy48:
#line 96 "scan.re2c"
	{ TOK(IDENT); }
#line 364 "scan.c"
yy49:
	++ctx->cursor;
#line 66 "scan.re2c"
	{ TOK(LBRACKET); }
#line 369 "scan.c"
yy51:
	++ctx->cursor;
#line 67 "scan.re2c"
	{ TOK(RBRACKET); }
#line 374 "scan.c"
yy53:
	++ctx->cursor;
#line 58 "scan.re2c"
	{ TOK(XOR_BW); }
#line 379 "scan.c"
yy55:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy102;
	default:	goto yy47;
	}
yy56:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy103;
	default:	goto yy47;
	}
yy57:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy104;
	case 'o':	goto yy105;
	default:	goto yy47;
	}
yy58:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy107;
	case 'n':	goto yy108;
	default:	goto yy47;
	}
yy59:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy109;
	case 'o':	goto yy110;
	case 'u':	goto yy111;
	default:	goto yy47;
	}
yy60:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy112;
	case 'm':	goto yy114;
	case 'n':	goto yy115;
	default:	goto yy47;
	}
yy61:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy117;
	default:	goto yy47;
	}
yy62:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy118;
	default:	goto yy47;
	}
yy63:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy119;
	default:	goto yy47;
	}
yy64:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy121;
	default:	goto yy47;
	}
yy65:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy122;
	default:	goto yy47;
	}
yy66:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy123;
	case 'r':	goto yy124;
	default:	goto yy47;
	}
yy67:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy125;
	default:	goto yy47;
	}
yy68:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'h':	goto yy126;
	default:	goto yy47;
	}
yy69:
	++ctx->cursor;
#line 68 "scan.re2c"
	{ TOK(LBRACE); }
#line 475 "scan.c"
yy71:
	yych = *++ctx->cursor;
	switch (yych) {
	case '|':	goto yy127;
	default:	goto yy72;
	}
yy72:
#line 57 "scan.re2c"
	{ TOK(OR_BW); }
#line 485 "scan.c"
yy73:
	++ctx->cursor;
#line 69 "scan.re2c"
	{ TOK(RBRACE); }
#line 490 "scan.c"
yy75:
	++ctx->cursor;
#line 60 "scan.re2c"
	{ TOK(NOT_BW); }
#line 495 "scan.c"
yy77:
	++ctx->cursor;
#line 42 "scan.re2c"
	{ TOK(NEQ); }
#line 500 "scan.c"
yy79:
	++ctx->cursor;
#line 54 "scan.re2c"
	{ TOK(AND); }
#line 505 "scan.c"
yy81:
	++ctx->cursor;
#line 70 "scan.re2c"
	{ TOK(RARROW); }
#line 510 "scan.c"
yy83:
	yych = *++ctx->cursor;
	switch (yych) {
	case '\n':	goto yy129;
	default:	goto yy83;
	}
yy85:
	yych = *++ctx->cursor;
yy86:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy85;
	default:	goto yy32;
	}
yy87:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy131;
	default:	goto yy88;
	}
yy88:
	ctx->cursor = marker;
	goto yy32;
yy89:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy134;
	default:	goto yy88;
	}
yy90:
	++ctx->cursor;
#line 71 "scan.re2c"
	{ TOK(LARROW); }
#line 572 "scan.c"
yy92:
	++ctx->cursor;
#line 52 "scan.re2c"
	{ TOK(LSH); }
#line 577 "scan.c"
yy94:
	++ctx->cursor;
#line 45 "scan.re2c"
	{ TOK(LTEQ); }
#line 582 "scan.c"
yy96:
	++ctx->cursor;
#line 41 "scan.re2c"
	{ TOK(EQ); }
#line 587 "scan.c"
yy98:
	++ctx->cursor;
#line 46 "scan.re2c"
	{ TOK(GTEQ); }
#line 592 "scan.c"
yy100:
	++ctx->cursor;
#line 53 "scan.re2c"
	{ TOK(RSH); }
#line 597 "scan.c"
yy102:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'g':	goto yy137;
	default:	goto yy47;
	}
yy103:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy138;
	default:	goto yy47;
	}
yy104:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy139;
	default:	goto yy47;
	}
yy105:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy106;
	}
yy106:
#line 87 "scan.re2c"
	{ TOK(KW_DO); }
#line 687 "scan.c"
yy107:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy141;
	case 's':	goto yy142;
	default:	goto yy47;
	}
yy108:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy143;
	default:	goto yy47;
	}
yy109:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy145;
	default:	goto yy47;
	}
yy110:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy146;
	default:	goto yy47;
	}
yy111:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy148;
	default:	goto yy47;
	}
yy112:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy113;
	}
yy113:
#line 81 "scan.re2c"
	{ TOK(KW_IF); }
#line 790 "scan.c"
yy114:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'p':	goto yy150;
	default:	goto yy47;
	}
yy115:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy116;
	}
yy116:
#line 80 "scan.re2c"
	{ TOK(KW_IN); }
#line 868 "scan.c"
yy117:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy151;
	default:	goto yy47;
	}
yy118:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'd':	goto yy153;
	default:	goto yy47;
	}
yy119:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy120;
	}
yy120:
#line 86 "scan.re2c"
	{ TOK(KW_OF); }
#line 952 "scan.c"
yy121:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy154;
	default:	goto yy47;
	}
yy122:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'a':	goto yy155;
	case 'r':	goto yy156;
	default:	goto yy47;
	}
yy123:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy157;
	default:	goto yy47;
	}
yy124:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy158;
	default:	goto yy47;
	}
yy125:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy159;
	default:	goto yy47;
	}
yy126:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy161;
	default:	goto yy47;
	}
yy127:
	++ctx->cursor;
#line 56 "scan.re2c"
	{ TOK(OR); }
#line 994 "scan.c"
yy129:
	++ctx->cursor;
#line 31 "scan.re2c"
	{
        ++ctx->line;
        goto next_token_start;
    }
#line 1002 "scan.c"
yy131:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':	goto yy131;
	default:	goto yy133;
	}
yy133:
#line 97 "scan.re2c"
	{ TOK(BIN); }
#line 1013 "scan.c"
yy134:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy134;
	default:	goto yy136;
	}
yy136:
#line 100 "scan.re2c"
	{ TOK(HEX); }
#line 1044 "scan.c"
yy137:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy162;
	default:	goto yy47;
	}
yy138:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy163;
	default:	goto yy47;
	}
yy139:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy140;
	}
yy140:
#line 78 "scan.re2c"
	{ TOK(KW_DEF); }
#line 1128 "scan.c"
yy141:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'f':	goto yy165;
	default:	goto yy47;
	}
yy142:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy167;
	default:	goto yy47;
	}
yy143:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy144;
	}
yy144:
#line 73 "scan.re2c"
	{ TOK(KW_END); }
#line 1212 "scan.c"
yy145:
	yych = *++ctx->cursor;
	switch (yych) {
	case 's':	goto yy169;
	default:	goto yy47;
	}
yy146:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy147;
	}
yy147:
#line 88 "scan.re2c"
	{ TOK(KW_FOR); }
#line 1290 "scan.c"
yy148:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy149;
	}
yy149:
#line 77 "scan.re2c"
	{ TOK(KW_FUN); }
#line 1362 "scan.c"
yy150:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'o':	goto yy170;
	default:	goto yy47;
	}
yy151:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy152;
	}
yy152:
#line 79 "scan.re2c"
	{ TOK(KW_LET); }
#line 1440 "scan.c"
yy153:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy171;
	default:	goto yy47;
	}
yy154:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy172;
	default:	goto yy47;
	}
yy155:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy174;
	default:	goto yy47;
	}
yy156:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'u':	goto yy175;
	default:	goto yy47;
	}
yy157:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy176;
	default:	goto yy47;
	}
yy158:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy178;
	default:	goto yy47;
	}
yy159:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy160;
	}
yy160:
#line 90 "scan.re2c"
	{ TOK(KW_MUT); }
#line 1548 "scan.c"
yy161:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy180;
	default:	goto yy47;
	}
yy162:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'n':	goto yy181;
	default:	goto yy47;
	}
yy163:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy164;
	}
yy164:
#line 85 "scan.re2c"
	{ TOK(KW_CASE); }
#line 1632 "scan.c"
yy165:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy166;
	}
yy166:
#line 83 "scan.re2c"
	{ TOK(KW_ELIF); }
#line 1704 "scan.c"
yy167:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy168;
	}
yy168:
#line 84 "scan.re2c"
	{ TOK(KW_ELSE); }
#line 1776 "scan.c"
yy169:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy183;
	default:	goto yy47;
	}
yy170:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'r':	goto yy185;
	default:	goto yy47;
	}
yy171:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'l':	goto yy186;
	default:	goto yy47;
	}
yy172:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy173;
	}
yy173:
#line 92 "scan.re2c"
	{ TOK(KW_PURE); }
#line 1866 "scan.c"
yy174:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'i':	goto yy187;
	default:	goto yy47;
	}
yy175:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy188;
	default:	goto yy47;
	}
yy176:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy177;
	}
yy177:
#line 82 "scan.re2c"
	{ TOK(KW_THEN); }
#line 1950 "scan.c"
yy178:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy179;
	}
yy179:
#line 93 "scan.re2c"
	{ TOK(KW_TRUE); }
#line 2022 "scan.c"
yy180:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy189;
	default:	goto yy47;
	}
yy181:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy182;
	}
yy182:
#line 72 "scan.re2c"
	{ TOK(KW_BEGIN); }
#line 2100 "scan.c"
yy183:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy184;
	}
yy184:
#line 94 "scan.re2c"
	{ TOK(KW_FALSE); }
#line 2172 "scan.c"
yy185:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy191;
	default:	goto yy47;
	}
yy186:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'e':	goto yy193;
	default:	goto yy47;
	}
yy187:
	yych = *++ctx->cursor;
	switch (yych) {
	case 'c':	goto yy195;
	default:	goto yy47;
	}
yy188:
	yych = *++ctx->cursor;
	switch (yych) {
	case 't':	goto yy197;
	default:	goto yy47;
	}
yy189:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy190;
	}
yy190:
#line 89 "scan.re2c"
	{ TOK(KW_WHILE); }
#line 2268 "scan.c"
yy191:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy192;
	}
yy192:
#line 75 "scan.re2c"
	{ TOK(KW_IMPORT); }
#line 2340 "scan.c"
yy193:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy194;
	}
yy194:
#line 74 "scan.re2c"
	{ TOK(KW_MODULE); }
#line 2412 "scan.c"
yy195:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy196;
	}
yy196:
#line 91 "scan.re2c"
	{ TOK(KW_STATIC); }
#line 2484 "scan.c"
yy197:
	yych = *++ctx->cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy198;
	}
yy198:
#line 76 "scan.re2c"
	{ TOK(KW_STRUCT); }
#line 2556 "scan.c"
}
#line 101 "scan.re2c"

}
